/* eslint-disable no-magic-numbers */

import js from '@eslint/js'
import globals from 'globals'

export default [
    {
        files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
        extends: [js.configs.recommended],
        languageOptions: {
            ecmaVersion: 2020,
            globals: globals.browser,
        },
        rules: {
            'array-callback-return': 'warn',
            'no-constructor-return': 'warn',
            'no-duplicate-imports': 'warn',
            'no-loss-of-precision': 'warn',
            'no-self-compare': 'warn',
            'no-template-curly-in-string': 'warn',
            'no-unassigned-vars': 'warn',
            'no-unreachable-loop': 'error',
            'no-useless-assignment': 'warn',

            'accessor-pairs': 'warn',
            'block-scoped-var': 'warn',
            camelcase: 'warn',
            'class-methods-use-this': 'warn',
            complexity: 'warn',
            'default-case': 'warn',
            'default-case-last': 'warn',
            'default-param-last': 'warn',
            'dot-notation': 'warn',
            eqeqeq: ['warn', 'always'],
            'func-name-matching': 'warn',
            'func-style': ['warn', 'expression'],
            'grouped-accessor-pairs': 'warn',
            // x, y, z are disallowed so there are not 2 warnings for them, because they are in the denylist
            'id-length': [
                'warn',
                { min: 2, max: 30, exceptions: ['e', 'i', 'j', 'a', 'b', '_', 'x', 'y', 'z'] },
            ],
            'id-denylist': ['warn', 'foo', 'bar', 'baz', 'x', 'y', 'z'],
            'logical-assignment-operators': 'warn',
            'max-depth': ['warn', 4],
            'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }],
            'max-lines-per-function': ['warn', { max: 50, skipBlankLines: true, skipComments: true }],
            'max-nested-callbacks': ['warn', 5],
            'new-cap': 'warn',
            'no-alert': 'warn',
            'no-array-constructor': 'warn',
            'no-bitwise': 'warn',
            'no-case-declarations': 'warn',
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-continue': 'warn',
            'no-delete-var': 'warn',
            'no-div-regex': 'warn',
            'no-else-return': 'warn',
            'no-empty': 'warn',
            'no-empty-function': 'warn',
            'no-empty-static-block': 'warn',
            'no-eq-null': 'warn',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-boolean-cast': 'warn',
            'no-extra-label': 'warn',
            'no-global-assign': 'error',
            'no-implicit-coercion': 'warn',
            'no-implicit-globals': 'warn',
            'no-implied-eval': 'error',
            'no-label-var': 'warn',
            'no-lone-blocks': 'warn',
            'no-lonely-if': 'warn',
            'no-loop-func': 'warn',
            'no-magic-numbers': [
                'warn',
                {
                    ignore: [-1, 0, 1, 2, 100, 1000],
                    ignoreArrayIndexes: true,
                    ignoreDefaultValues: true,
                    ignoreClassFieldInitialValues: true,
                    enforceConst: true,
                },
            ],
            'no-multi-assign': 'warn',
            'no-multi-str': 'warn',
            'no-negated-condition': 'warn',
            'no-nested-ternary': 'warn',
            'no-new': 'warn',
            'no-new-func': 'warn',
            'no-new-wrappers': 'warn',
            'no-nonoctal-decimal-escape': 'warn',
            'no-object-constructor': 'warn',
            'no-octal': 'warn',
            'no-octal-escape': 'warn',
            'no-redeclare': 'error',
            'no-regex-spaces': 'warn',
            'no-restricted-exports': [
                'warn',
                { restrictedNamedExports: ['foo', 'bar', 'baz', 'x', 'y', 'z', 'a', 'b', 'c'] },
            ],
            'no-return-assign': 'warn',
            'no-script-url': 'warn',
            'no-sequences': 'warn',
            'no-shadow': 'warn',
            'no-shadow-restricted-names': 'error',
            'no-throw-literal': 'warn',
            'no-undef-init': 'warn',
            'no-undefined': 'error',
            'no-underscore-dangle': 'warn',
            'no-unneeded-ternary': 'warn',
            'no-unused-expressions': 'warn',
            'no-unused-labels': 'warn',
            'no-useless-call': 'warn',
            'no-useless-catch': 'warn',
            'no-useless-computed-key': 'warn',
            'no-useless-concat': 'warn',
            'no-useless-constructor': 'warn',
            'no-useless-escape': 'warn',
            'no-useless-rename': 'warn',
            'no-useless-return': 'warn',
            'no-var': 'warn',
            'no-void': ['warn', { allowAsStatement: true }],
            'no-warning-comments': 'warn',
            'no-with': 'error',
            'object-shorthand': ['warn', 'always'],
            'operator-assignment': ['warn', 'always'],
            'prefer-arrow-callback': 'warn',
            'prefer-const': 'warn',
            'prefer-destructuring': ['warn', { object: true, array: false }],
            'prefer-exponentiation-operator': 'warn',
            'prefer-object-has-own': 'warn',
            'prefer-object-spread': 'warn',
            'prefer-promise-reject-errors': 'warn',
            'prefer-rest-params': 'warn',
            'prefer-spread': 'warn',
            'prefer-template': 'warn',
            'preserve-caught-error': 'warn',
            // radix: 'warn',
            'require-await': 'warn',
            'require-unicode-regexp': 'warn',
            'require-yield': 'warn',
            'symbol-description': 'warn',
            'vars-on-top': 'warn',
            yoda: ['warn', 'never', { exceptRange: true }],
        },
    },
    {
        files: ['**/*.{jsx,tsx}'],
        rules: {
            'max-lines-per-function': ['warn', { max: 120, skipBlankLines: true, skipComments: true }],
        },
    },
]
