import eslintReact from '@eslint-react/eslint-plugin'
import reactRefresh from 'eslint-plugin-react-refresh'

export default [
    {
        files: ['**/*.{jsx,tsx}'],
        extends: [reactRefresh.configs.vite],
    },
    {
        files: ['**/*.{tsx,ts,jsx,js}'],
        extends: [eslintReact.configs['recommended-typescript']],
        rules: {
            '@eslint-react/error-boundaries': 'error',
            '@eslint-react/exhaustive-deps': 'warn',
            '@eslint-react/globals': 'error',
            '@eslint-react/immutability': 'error',
            '@eslint-react/no-access-state-in-setstate': 'warn',
            '@eslint-react/no-array-index-key': 'warn',
            '@eslint-react/no-children-count': 'warn',
            '@eslint-react/no-children-for-each': 'warn',
            '@eslint-react/no-children-map': 'warn',
            '@eslint-react/no-children-only': 'warn',
            '@eslint-react/no-children-to-array': 'warn',
            '@eslint-react/no-class-component': 'warn',
            '@eslint-react/no-clone-element': 'warn',
            '@eslint-react/no-context-provider': 'warn',
            '@eslint-react/no-duplicate-key': 'warn',
            '@eslint-react/no-forward-ref': 'warn',
            '@eslint-react/no-leaked-conditional-rendering': 'warn',
            '@eslint-react/no-missing-component-display-name': 'warn',
            '@eslint-react/no-missing-context-display-name': 'warn',
            '@eslint-react/no-missing-key': 'error',
            '@eslint-react/no-nested-component-definitions': 'error',
            '@eslint-react/no-nested-lazy-component-declarations': 'warn',
            '@eslint-react/no-unnecessary-use-prefix': 'warn',
            '@eslint-react/no-unstable-context-value': 'warn',
            '@eslint-react/no-unstable-default-props': 'warn',
            '@eslint-react/no-use-context': 'warn',
            '@eslint-react/purity': 'warn',
            '@eslint-react/refs': 'warn',
            '@eslint-react/rules-of-hooks': 'warn',
            '@eslint-react/set-state-in-effect': 'warn',
            '@eslint-react/set-state-in-render': 'error',
            '@eslint-react/static-components': 'warn',
            '@eslint-react/unsupported-syntax': 'warn',
            '@eslint-react/use-memo': 'warn',
            '@eslint-react/use-state': 'warn',

            '@eslint-react/jsx-no-children-prop': 'warn',
            '@eslint-react/jsx-no-children-prop-with-children': 'warn',
            '@eslint-react/jsx-no-comment-textnodes': 'warn',
            '@eslint-react/jsx-no-key-after-spread': 'warn',
            '@eslint-react/jsx-no-leaked-dollar': 'warn',
            '@eslint-react/jsx-no-leaked-semicolon': 'warn',
            '@eslint-react/jsx-no-namespace': 'warn',

            '@eslint-react/rsc-function-definition': 'warn',

            '@eslint-react/dom-no-dangerously-set-innerhtml': 'error',
            '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'warn',
            '@eslint-react/dom-no-find-dom-node': 'warn',
            '@eslint-react/dom-no-hydrate': 'warn',
            '@eslint-react/dom-no-missing-iframe-sandbox': 'error',
            '@eslint-react/dom-no-render': 'warn',
            '@eslint-react/dom-no-render-return-value': 'warn',
            '@eslint-react/dom-no-script-url': 'error',
            '@eslint-react/dom-no-string-style-prop': 'warn',
            '@eslint-react/dom-no-unknown-property': 'warn',
            '@eslint-react/dom-no-unsafe-iframe-sandbox': 'error',
            '@eslint-react/dom-no-unsafe-target-blank': 'warn',
            '@eslint-react/dom-no-use-form-state': 'warn',
            '@eslint-react/dom-no-void-elements-with-children': 'warn',

            '@eslint-react/web-api-no-leaked-event-listener': 'warn',
            '@eslint-react/web-api-no-leaked-fetch': 'warn',
            '@eslint-react/web-api-no-leaked-interval': 'warn',
            '@eslint-react/web-api-no-leaked-resize-observer': 'warn',
            '@eslint-react/web-api-no-leaked-timeout': 'warn',

            '@eslint-react/naming-convention-context-name': 'warn',
            '@eslint-react/naming-convention-id-name': 'warn',
            '@eslint-react/naming-convention-ref-name': 'warn',
        },
    },
]
